function createfigure(X1, Y1, Y2)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 24-Oct-2017 16:56:03

% Create figure
figure1 = figure('PaperOrientation','landscape','pos',[10 10 560 450],'PaperSize',[20 13]);
%figure1 = figure('PaperOrientation','landscape','PaperSize',[16 12]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');
% xlim(axes1,[-5 5]);
 %ylim(axes1,[-100 10]);
% Create plot
plot(X1,Y1,'DisplayName','Numerical','LineWidth',2,...
    'Color',[0 0.447058826684952 0.74117648601532]);

hold all
plot(X1,Y2,'DisplayName','Analytical','LineWidth',2,'LineStyle','--',...
    'Color',[0.87058824300766 0.490196079015732 0]);
%    'Color',[0 0.447058826684952 0.74117648601532]); %
%    


box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',13,'TickLabelInterpreter','latex','XGrid','on','YGrid',...
    'on');
% Create xlabel
xlabel({'$$x$$'},'FontSize',20,'Interpreter','latex');

% Create ylabel
%ylabel({'\rho'},'FontSize',20,'Rotation',0);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Interpreter','latex','FontSize',17);
% Create textarrow
annotation(figure1,'textarrow',[0.048 0.1],...
    [0.55 0.865459627329192],'TextEdgeColor','none',...
    'FontSize',20,...
    'FontName','TeX Gyre Bonum',...
    'String',{'$$\frac{\delta \mathcal{F}}{\delta \rho}$$'},...
    'Interpreter','latex',...
    'HeadStyle','none',...
    'LineStyle','none');
%$$\frac{\delta \mathcal{F}}{\delta \rho}$$
%$$\rho$$
%$$\rho\,u$$

% annotation(figure1,'textarrow',[0.531649810366625 0.868],...
%     [0.04 0.265459627329192],'TextEdgeColor','none',...
%     'FontSize',18,...
%     'FontName','TeX Gyre Bonum',...
%     'String',{'x'},...
%     'HeadStyle','none',...
%     'LineStyle','none');

% This options are for images of presentations
set(gcf, 'PaperPosition', [0 0 17 12]);
set(gcf, 'PaperSize', [17 12]); %Set the paper to have width 5 and height 5.
%saveas(gcf, 'p2doublewellantifreeenergy', 'pdf') %Save figure
